language: node_js
node_js:
  - 8
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - "./node_modules"
script:
  - ts-node ./scripts/builder.ts

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
